/**
 * Assembles the publishable @lumina/tailwind package into dist/. The preset and
 * theme are generated by the tokens build (this project's `build` target
 * dependsOn `tokens`), so they are guaranteed fresh here.
 */
import { copyFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const OUT = resolve(ROOT, '../../dist/libs/tailwind');

mkdirSync(OUT, { recursive: true });
for (const file of ['preset.cjs', 'theme.css', 'package.json', 'README.md']) {
  copyFileSync(resolve(ROOT, file), resolve(OUT, file));
}
console.log('✓ @lumina/tailwind packaged →', OUT);
