/**
 * Lumina UI — design token build.
 *
 * Compiles the DTCG token source (primitive → semantic → component) into:
 *   • CSS custom properties, one layer per theme (light / dark / high-contrast)
 *   • A typed TypeScript token map for safe, autocompleted consumption in Angular
 *
 * Themes share identical *semantic* token names; only their references to
 * primitives differ. Semantic + component layers are emitted with
 * `outputReferences: true`, so they compile to live `var(--lui-…)` chains that
 * resolve against the primitive layer at runtime — the mechanism that lets a
 * single `data-theme` swap re-theme the entire app with zero re-paint cost.
 */
import StyleDictionary from 'style-dictionary';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import {
  buildNestedJson,
  buildPresetExtend,
  buildThemeCss,
} from './tailwind-map.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const PREFIX = 'lui';

const CSS_OUT = 'src/generated/css/';
const TS_OUT = 'src/generated/ts/';
const JSON_OUT = 'src/generated/json/';
// The @lumina/tailwind package sits alongside @lumina/tokens; its preset and
// v4 theme are generated straight into it (committed, like the CSS).
const TW_OUT = '../tailwind/';

const THEMES = [
  { name: 'light', selector: ':root, [data-theme="light"]' },
  { name: 'dark', selector: '[data-theme="dark"]' },
  { name: 'hc', selector: '[data-theme="hc"]' },
];

/** A lean, predictable CSS transform group — our source values are already
 *  CSS-ready strings/numbers, so we deliberately avoid the default `css` group's
 *  numeric size/time transforms that would mangle pre-unitised values. */
StyleDictionary.registerTransformGroup({
  // Colors are authored in OKLCH (already valid CSS), so we deliberately omit
  // `color/css` — its tinycolor normalisation does not understand oklch() and
  // would mangle the values. Every other value is emitted verbatim.
  name: 'lumina/css',
  transforms: [
    'attribute/cti',
    'name/kebab',
    'cubicBezier/css',
    'fontFamily/css',
  ],
});

const isThemed = (token) =>
  token.filePath.includes('semantic') || token.filePath.includes('component');

/** TypeScript format: a frozen, fully-typed map of consumable token → CSS var(). */
StyleDictionary.registerFormat({
  name: 'lumina/ts-tokens',
  format: ({ dictionary }) => {
    const entries = dictionary.allTokens
      .filter(isThemed)
      .map(
        (t) =>
          `  '${t.path.join('.')}': 'var(--${[PREFIX, ...t.path].join('-')})',`,
      )
      .sort();
    return `/* AUTO-GENERATED by libs/tokens/scripts/build-tokens.mjs — do not edit. */

/**
 * Theme-aware design tokens as CSS \`var()\` references.
 * Resolves against whichever theme is active on \`document.documentElement\`.
 */
export const tokens = {
${entries.join('\n')}
} as const;

export type TokenName = keyof typeof tokens;

/** Resolve a token name to its CSS \`var(--lui-…)\` reference. */
export function token(name: TokenName): string {
  return tokens[name];
}

/** The set of themes Lumina ships out of the box. */
export const BUILT_IN_THEMES = ['light', 'dark', 'hc'] as const;
export type BuiltInTheme = (typeof BUILT_IN_THEMES)[number];
`;
  },
});

/** Portable JSON: a nested map of fully-resolved token values. */
StyleDictionary.registerFormat({
  name: 'lumina/json-nested',
  format: ({ dictionary }) =>
    `${JSON.stringify(buildNestedJson(dictionary.allTokens), null, 2)}\n`,
});

/** Tailwind v3 preset — theme.extend of live var(--lui-…) references. */
StyleDictionary.registerFormat({
  name: 'lumina/tailwind-preset',
  format: ({ dictionary }) => {
    const extend = buildPresetExtend(dictionary.allTokens);
    return `/* AUTO-GENERATED by libs/tokens/scripts/build-tokens.mjs — do not edit. */

/**
 * Lumina UI — Tailwind v3 preset.
 *
 * Every value is a live \`var(--lui-…)\` reference, so utilities such as
 * \`bg-accent\` or \`text-fg-muted\` track the active \`data-theme\` and the runtime
 * accent exactly like the Angular components. Tailwind-friendly, never required.
 *
 * @example
 *   // tailwind.config.js
 *   module.exports = { presets: [require('@lumina/tailwind')] };
 */
module.exports = ${JSON.stringify({ theme: { extend } }, null, 2)};
`;
  },
});

/** Tailwind v4 theme — CSS custom properties in Tailwind's own namespaces. */
StyleDictionary.registerFormat({
  name: 'lumina/tailwind-theme',
  format: ({ dictionary }) =>
    `/* AUTO-GENERATED by libs/tokens/scripts/build-tokens.mjs — do not edit. */

/**
 * Lumina UI — Tailwind v4 theme. Import after Tailwind itself:
 *   @import 'tailwindcss';
 *   @import '@lumina/tailwind/theme.css';
 * Values are var(--lui-…) references, so utilities follow the active theme.
 */
@theme {
${buildThemeCss(dictionary.allTokens)}
}
`,
});

async function buildPrimitives() {
  const sd = new StyleDictionary({
    source: [`${ROOT}/tokens/primitive/**/*.json`],
    platforms: {
      css: {
        transformGroup: 'lumina/css',
        prefix: PREFIX,
        buildPath: `${ROOT}/${CSS_OUT}`,
        files: [
          {
            destination: '_primitives.css',
            format: 'css/variables',
            options: { selector: ':root', outputReferences: false },
          },
        ],
      },
      json: {
        transformGroup: 'lumina/css',
        prefix: PREFIX,
        buildPath: `${ROOT}/${JSON_OUT}`,
        files: [
          { destination: 'primitives.json', format: 'lumina/json-nested' },
        ],
      },
    },
  });
  await sd.buildAllPlatforms();
}

async function buildTheme({ name, selector }, { emitTs }) {
  const sd = new StyleDictionary({
    // Semantic/component layers intentionally reference the primitive layer,
    // which is filtered out of these files (it lives in `_primitives.css`).
    // That is exactly how cross-theme `var()` chains are produced, so silence
    // the expected "filtered out references" notice while keeping errors.
    log: { warnings: 'disabled' },
    source: [
      `${ROOT}/tokens/primitive/**/*.json`,
      // `${name}.json` plus any sibling `${name}.*.json` layer files (e.g. surfaces).
      `${ROOT}/tokens/semantic/${name}*.json`,
      `${ROOT}/tokens/component/**/*.json`,
    ],
    platforms: {
      css: {
        transformGroup: 'lumina/css',
        prefix: PREFIX,
        buildPath: `${ROOT}/${CSS_OUT}`,
        files: [
          {
            destination: `theme-${name}.css`,
            format: 'css/variables',
            filter: isThemed,
            options: { selector, outputReferences: true },
          },
        ],
      },
      json: {
        transformGroup: 'lumina/css',
        prefix: PREFIX,
        buildPath: `${ROOT}/${JSON_OUT}`,
        files: [
          {
            destination: `semantic.${name}.json`,
            format: 'lumina/json-nested',
            filter: isThemed,
          },
        ],
      },
      // The Tailwind artifacts are theme-agnostic (they emit var() references,
      // not resolved values), so we generate them once, from the light build
      // that carries the full primitive + semantic + component token set.
      ...(emitTs
        ? {
            ts: {
              transformGroup: 'lumina/css',
              prefix: PREFIX,
              buildPath: `${ROOT}/${TS_OUT}`,
              files: [{ destination: 'tokens.ts', format: 'lumina/ts-tokens' }],
            },
            tailwind: {
              transformGroup: 'lumina/css',
              prefix: PREFIX,
              buildPath: `${ROOT}/${TW_OUT}`,
              files: [
                { destination: 'preset.cjs', format: 'lumina/tailwind-preset' },
                { destination: 'theme.css', format: 'lumina/tailwind-theme' },
              ],
            },
          }
        : {}),
    },
  });
  await sd.buildAllPlatforms();
}

async function main() {
  await buildPrimitives();
  for (const theme of THEMES) {
    await buildTheme(theme, { emitTs: theme.name === 'light' });
  }
  console.log('✓ Lumina tokens built:', THEMES.map((t) => t.name).join(', '));
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
