/**
 * Lumina UI — design token build.
 *
 * Compiles the DTCG token source (primitive → semantic → component) into:
 *   • CSS custom properties, one layer per theme (light / dark / high-contrast)
 *   • A typed TypeScript token map for safe, autocompleted consumption in Angular
 *
 * Themes share identical *semantic* token names; only their references to
 * primitives differ. Semantic + component layers are emitted with
 * `outputReferences: true`, so they compile to live `var(--lui-…)` chains that
 * resolve against the primitive layer at runtime — the mechanism that lets a
 * single `data-theme` swap re-theme the entire app with zero re-paint cost.
 */
import StyleDictionary from 'style-dictionary';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const PREFIX = 'lui';

const CSS_OUT = 'src/generated/css/';
const TS_OUT = 'src/generated/ts/';

const THEMES = [
  { name: 'light', selector: ':root, [data-theme="light"]' },
  { name: 'dark', selector: '[data-theme="dark"]' },
  { name: 'hc', selector: '[data-theme="hc"]' },
];

/** A lean, predictable CSS transform group — our source values are already
 *  CSS-ready strings/numbers, so we deliberately avoid the default `css` group's
 *  numeric size/time transforms that would mangle pre-unitised values. */
StyleDictionary.registerTransformGroup({
  name: 'lumina/css',
  transforms: [
    'attribute/cti',
    'name/kebab',
    'color/css',
    'cubicBezier/css',
    'fontFamily/css',
  ],
});

const isThemed = (token) =>
  token.filePath.includes('semantic') || token.filePath.includes('component');

/** TypeScript format: a frozen, fully-typed map of consumable token → CSS var(). */
StyleDictionary.registerFormat({
  name: 'lumina/ts-tokens',
  format: ({ dictionary }) => {
    const entries = dictionary.allTokens
      .filter(isThemed)
      .map(
        (t) =>
          `  '${t.path.join('.')}': 'var(--${[PREFIX, ...t.path].join('-')})',`,
      )
      .sort();
    return `/* AUTO-GENERATED by libs/tokens/scripts/build-tokens.mjs — do not edit. */

/**
 * Theme-aware design tokens as CSS \`var()\` references.
 * Resolves against whichever theme is active on \`document.documentElement\`.
 */
export const tokens = {
${entries.join('\n')}
} as const;

export type TokenName = keyof typeof tokens;

/** Resolve a token name to its CSS \`var(--lui-…)\` reference. */
export function token(name: TokenName): string {
  return tokens[name];
}

/** The set of themes Lumina ships out of the box. */
export const BUILT_IN_THEMES = ['light', 'dark', 'hc'] as const;
export type BuiltInTheme = (typeof BUILT_IN_THEMES)[number];
`;
  },
});

async function buildPrimitives() {
  const sd = new StyleDictionary({
    source: [`${ROOT}/tokens/primitive/**/*.json`],
    platforms: {
      css: {
        transformGroup: 'lumina/css',
        prefix: PREFIX,
        buildPath: `${ROOT}/${CSS_OUT}`,
        files: [
          {
            destination: '_primitives.css',
            format: 'css/variables',
            options: { selector: ':root', outputReferences: false },
          },
        ],
      },
    },
  });
  await sd.buildAllPlatforms();
}

async function buildTheme({ name, selector }, { emitTs }) {
  const sd = new StyleDictionary({
    // Semantic/component layers intentionally reference the primitive layer,
    // which is filtered out of these files (it lives in `_primitives.css`).
    // That is exactly how cross-theme `var()` chains are produced, so silence
    // the expected "filtered out references" notice while keeping errors.
    log: { warnings: 'disabled' },
    source: [
      `${ROOT}/tokens/primitive/**/*.json`,
      `${ROOT}/tokens/semantic/${name}.json`,
      `${ROOT}/tokens/component/**/*.json`,
    ],
    platforms: {
      css: {
        transformGroup: 'lumina/css',
        prefix: PREFIX,
        buildPath: `${ROOT}/${CSS_OUT}`,
        files: [
          {
            destination: `theme-${name}.css`,
            format: 'css/variables',
            filter: isThemed,
            options: { selector, outputReferences: true },
          },
        ],
      },
      ...(emitTs
        ? {
            ts: {
              transformGroup: 'lumina/css',
              prefix: PREFIX,
              buildPath: `${ROOT}/${TS_OUT}`,
              files: [{ destination: 'tokens.ts', format: 'lumina/ts-tokens' }],
            },
          }
        : {}),
    },
  });
  await sd.buildAllPlatforms();
}

async function main() {
  await buildPrimitives();
  for (const theme of THEMES) {
    await buildTheme(theme, { emitTs: theme.name === 'light' });
  }
  console.log('✓ Lumina tokens built:', THEMES.map((t) => t.name).join(', '));
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
