/* AUTO-GENERATED by libs/tokens/scripts/build-tokens.mjs — do not edit. */

/**
 * Lumina UI — Tailwind v3 preset.
 *
 * Every value is a live `var(--lui-…)` reference, so utilities such as
 * `bg-accent` or `text-fg-muted` track the active `data-theme` and the runtime
 * accent exactly like the Angular components. Tailwind-friendly, never required.
 *
 * @example
 *   // tailwind.config.js
 *   module.exports = { presets: [require('@lumina/tailwind')] };
 */
module.exports = {
  "theme": {
    "extend": {
      "colors": {
        "white": "var(--lui-color-white)",
        "black": "var(--lui-color-black)",
        "transparent": "var(--lui-color-transparent)",
        "neutral": {
          "50": "var(--lui-color-neutral-50)",
          "100": "var(--lui-color-neutral-100)",
          "200": "var(--lui-color-neutral-200)",
          "300": "var(--lui-color-neutral-300)",
          "400": "var(--lui-color-neutral-400)",
          "500": "var(--lui-color-neutral-500)",
          "600": "var(--lui-color-neutral-600)",
          "700": "var(--lui-color-neutral-700)",
          "800": "var(--lui-color-neutral-800)",
          "900": "var(--lui-color-neutral-900)",
          "950": "var(--lui-color-neutral-950)"
        },
        "brand": {
          "50": "var(--lui-color-brand-50)",
          "100": "var(--lui-color-brand-100)",
          "200": "var(--lui-color-brand-200)",
          "300": "var(--lui-color-brand-300)",
          "400": "var(--lui-color-brand-400)",
          "500": "var(--lui-color-brand-500)",
          "600": "var(--lui-color-brand-600)",
          "700": "var(--lui-color-brand-700)",
          "800": "var(--lui-color-brand-800)",
          "900": "var(--lui-color-brand-900)",
          "950": "var(--lui-color-brand-950)"
        },
        "success": {
          "50": "var(--lui-color-success-50)",
          "100": "var(--lui-color-success-100)",
          "200": "var(--lui-color-success-200)",
          "300": "var(--lui-color-success-300)",
          "400": "var(--lui-color-success-400)",
          "500": "var(--lui-color-success-500)",
          "600": "var(--lui-color-success-600)",
          "700": "var(--lui-color-success-700)",
          "800": "var(--lui-color-success-800)",
          "900": "var(--lui-color-success-900)",
          "950": "var(--lui-color-success-950)",
          "subtle": "var(--lui-color-success-subtle)",
          "DEFAULT": "var(--lui-color-success-default)",
          "hover": "var(--lui-color-success-hover)",
          "fg": "var(--lui-color-success-fg)",
          "text": "var(--lui-color-success-text)"
        },
        "warning": {
          "50": "var(--lui-color-warning-50)",
          "100": "var(--lui-color-warning-100)",
          "200": "var(--lui-color-warning-200)",
          "300": "var(--lui-color-warning-300)",
          "400": "var(--lui-color-warning-400)",
          "500": "var(--lui-color-warning-500)",
          "600": "var(--lui-color-warning-600)",
          "700": "var(--lui-color-warning-700)",
          "800": "var(--lui-color-warning-800)",
          "900": "var(--lui-color-warning-900)",
          "950": "var(--lui-color-warning-950)",
          "subtle": "var(--lui-color-warning-subtle)",
          "DEFAULT": "var(--lui-color-warning-default)",
          "hover": "var(--lui-color-warning-hover)",
          "fg": "var(--lui-color-warning-fg)",
          "text": "var(--lui-color-warning-text)"
        },
        "danger": {
          "50": "var(--lui-color-danger-50)",
          "100": "var(--lui-color-danger-100)",
          "200": "var(--lui-color-danger-200)",
          "300": "var(--lui-color-danger-300)",
          "400": "var(--lui-color-danger-400)",
          "500": "var(--lui-color-danger-500)",
          "600": "var(--lui-color-danger-600)",
          "700": "var(--lui-color-danger-700)",
          "800": "var(--lui-color-danger-800)",
          "900": "var(--lui-color-danger-900)",
          "950": "var(--lui-color-danger-950)",
          "subtle": "var(--lui-color-danger-subtle)",
          "DEFAULT": "var(--lui-color-danger-default)",
          "hover": "var(--lui-color-danger-hover)",
          "fg": "var(--lui-color-danger-fg)",
          "text": "var(--lui-color-danger-text)"
        },
        "info": {
          "50": "var(--lui-color-info-50)",
          "100": "var(--lui-color-info-100)",
          "200": "var(--lui-color-info-200)",
          "300": "var(--lui-color-info-300)",
          "400": "var(--lui-color-info-400)",
          "500": "var(--lui-color-info-500)",
          "600": "var(--lui-color-info-600)",
          "700": "var(--lui-color-info-700)",
          "800": "var(--lui-color-info-800)",
          "900": "var(--lui-color-info-900)",
          "950": "var(--lui-color-info-950)",
          "subtle": "var(--lui-color-info-subtle)",
          "DEFAULT": "var(--lui-color-info-default)",
          "hover": "var(--lui-color-info-hover)",
          "fg": "var(--lui-color-info-fg)",
          "text": "var(--lui-color-info-text)"
        },
        "surface": {
          "canvas": "var(--lui-color-bg-canvas)",
          "surface": "var(--lui-color-bg-surface)",
          "subtle": "var(--lui-color-bg-subtle)",
          "muted": "var(--lui-color-bg-muted)",
          "emphasis": "var(--lui-color-bg-emphasis)",
          "inverse": "var(--lui-color-bg-inverse)"
        },
        "fg": {
          "DEFAULT": "var(--lui-color-fg-default)",
          "muted": "var(--lui-color-fg-muted)",
          "subtle": "var(--lui-color-fg-subtle)",
          "disabled": "var(--lui-color-fg-disabled)",
          "inverse": "var(--lui-color-fg-inverse)",
          "link": "var(--lui-color-fg-link)"
        },
        "border": {
          "DEFAULT": "var(--lui-color-border-default)",
          "muted": "var(--lui-color-border-muted)",
          "strong": "var(--lui-color-border-strong)",
          "elevated": "var(--lui-color-border-elevated)"
        },
        "accent": {
          "subtle": "var(--lui-color-accent-subtle)",
          "muted": "var(--lui-color-accent-muted)",
          "DEFAULT": "var(--lui-color-accent-default)",
          "hover": "var(--lui-color-accent-hover)",
          "active": "var(--lui-color-accent-active)",
          "fg": "var(--lui-color-accent-fg)",
          "border": "var(--lui-color-accent-border)"
        },
        "focus": {
          "ring": "var(--lui-color-focus-ring)"
        },
        "overlay": {
          "scrim": "var(--lui-color-overlay-scrim)"
        }
      },
      "spacing": {
        "0": "var(--lui-space-0)",
        "1": "var(--lui-space-1)",
        "2": "var(--lui-space-2)",
        "3": "var(--lui-space-3)",
        "4": "var(--lui-space-4)",
        "5": "var(--lui-space-5)",
        "6": "var(--lui-space-6)",
        "7": "var(--lui-space-7)",
        "8": "var(--lui-space-8)",
        "10": "var(--lui-space-10)",
        "12": "var(--lui-space-12)",
        "16": "var(--lui-space-16)",
        "20": "var(--lui-space-20)",
        "24": "var(--lui-space-24)",
        "32": "var(--lui-space-32)",
        "px": "var(--lui-space-px)",
        "0-5": "var(--lui-space-0-5)",
        "1-5": "var(--lui-space-1-5)",
        "2-5": "var(--lui-space-2-5)",
        "3-5": "var(--lui-space-3-5)"
      },
      "borderRadius": {
        "none": "var(--lui-radius-none)",
        "xs": "var(--lui-radius-xs)",
        "sm": "var(--lui-radius-sm)",
        "md": "var(--lui-radius-md)",
        "lg": "var(--lui-radius-lg)",
        "xl": "var(--lui-radius-xl)",
        "2xl": "var(--lui-radius-2xl)",
        "3xl": "var(--lui-radius-3xl)",
        "full": "var(--lui-radius-full)"
      },
      "boxShadow": {
        "none": "var(--lui-shadow-none)",
        "xs": "var(--lui-shadow-xs)",
        "sm": "var(--lui-shadow-sm)",
        "md": "var(--lui-shadow-md)",
        "lg": "var(--lui-shadow-lg)",
        "xl": "var(--lui-shadow-xl)",
        "2xl": "var(--lui-shadow-2xl)"
      },
      "fontFamily": {
        "sans": "var(--lui-font-family-sans)",
        "mono": "var(--lui-font-family-mono)"
      },
      "fontSize": {
        "xs": "var(--lui-font-size-xs)",
        "sm": "var(--lui-font-size-sm)",
        "md": "var(--lui-font-size-md)",
        "lg": "var(--lui-font-size-lg)",
        "xl": "var(--lui-font-size-xl)",
        "2xl": "var(--lui-font-size-2xl)",
        "3xl": "var(--lui-font-size-3xl)",
        "4xl": "var(--lui-font-size-4xl)",
        "5xl": "var(--lui-font-size-5xl)"
      },
      "fontWeight": {
        "regular": "var(--lui-font-weight-regular)",
        "medium": "var(--lui-font-weight-medium)",
        "semibold": "var(--lui-font-weight-semibold)",
        "bold": "var(--lui-font-weight-bold)"
      },
      "lineHeight": {
        "none": "var(--lui-font-line-height-none)",
        "tight": "var(--lui-font-line-height-tight)",
        "snug": "var(--lui-font-line-height-snug)",
        "normal": "var(--lui-font-line-height-normal)",
        "relaxed": "var(--lui-font-line-height-relaxed)"
      },
      "letterSpacing": {
        "tighter": "var(--lui-font-letter-spacing-tighter)",
        "tight": "var(--lui-font-letter-spacing-tight)",
        "normal": "var(--lui-font-letter-spacing-normal)",
        "wide": "var(--lui-font-letter-spacing-wide)",
        "wider": "var(--lui-font-letter-spacing-wider)"
      },
      "zIndex": {
        "hide": "var(--lui-z-index-hide)",
        "base": "var(--lui-z-index-base)",
        "docked": "var(--lui-z-index-docked)",
        "dropdown": "var(--lui-z-index-dropdown)",
        "sticky": "var(--lui-z-index-sticky)",
        "overlay": "var(--lui-z-index-overlay)",
        "modal": "var(--lui-z-index-modal)",
        "popover": "var(--lui-z-index-popover)",
        "toast": "var(--lui-z-index-toast)",
        "tooltip": "var(--lui-z-index-tooltip)"
      },
      "transitionDuration": {
        "instant": "var(--lui-duration-instant)",
        "fast": "var(--lui-duration-fast)",
        "normal": "var(--lui-duration-normal)",
        "slow": "var(--lui-duration-slow)",
        "slower": "var(--lui-duration-slower)"
      },
      "transitionTimingFunction": {
        "linear": "var(--lui-easing-linear)",
        "standard": "var(--lui-easing-standard)",
        "emphasized": "var(--lui-easing-emphasized)",
        "decelerate": "var(--lui-easing-decelerate)",
        "accelerate": "var(--lui-easing-accelerate)"
      },
      "borderWidth": {
        "none": "var(--lui-border-width-none)",
        "thin": "var(--lui-border-width-thin)",
        "thick": "var(--lui-border-width-thick)",
        "heavy": "var(--lui-border-width-heavy)"
      },
      "opacity": {
        "0": "var(--lui-opacity-0)",
        "100": "var(--lui-opacity-100)",
        "disabled": "var(--lui-opacity-disabled)",
        "muted": "var(--lui-opacity-muted)",
        "hover": "var(--lui-opacity-hover)",
        "pressed": "var(--lui-opacity-pressed)"
      }
    }
  }
};
